language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '9'
  - '10'
scripts:
  - yarn coverage
after_success:
  - yarn coverage
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
