language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
scripts:
  - yarn coverage
after_success:
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
